global:
  owner: xiaodoli
  spaceName: xiaodoli
  envName: dev
  subscriptionName: xiaodoli
  subscriptionAlias: xdli
  productName: "devspace"
  productShortName: "space"
  resourceGroup: "azds-rg"
  components:
    cosmosdb:
      docDb: true
      mongoDb: false
      graphDb: false
kv:
  name: xiaodoli-kv
  resourceGroup: "azds-rg"
acr:
  resourceGroup: "azds-rg"
  email: xiaodoli@microsoft.com
aks:
  aksDnsPrefix: xiaodoli
  aksOwnerAadUpn: xiaodoli.onmicrosoft.com
  purpose: devspace
  clusterName: "xiaodoli-aks-dev"
  resourceGroup: "azds-rg"
  vmSize: Standard_D4s_v3
  nodeCount: 2
  version: "1.13.7"
  servicePrincipal: "App Center AKS AAD (non-production)"
  servicePrincipalPassword: "AppCenter-AKS-AADAppPwd"
  forceResetSpn: false
  clientAppName: "App Center AKS (non-production)"
  access:
    readers:
      - name: "Compliance Tooling Team"
        type: group
    contributors:
      - name: "1cs dri"
        type: group
    owners:
      - name: xiaodoli@microsoft.com
        type: user
  certs:
    - name: KeyVault-Certificate
    - name: Ssl-Certificate
    - name: Ssl-Aks-Default-Certificate
    - name: Geneva-Certificate
      type: geneva
    - name: KustoIngestion-Certificate
    - name: Api-Gateway-Ssl-Certificate
    - name: AppCenterSsl-Certificate
    - name: IngestionSsl-Certificate
    - name: Oauth-Token-Storage-Ssl-Certificate

servicebus:
  resourceGroup: "azds-rg"
terraform:
  resourceGroup: "azds-rg"
appInsights:
  resourceGroup: "azds-rg"
cosmosDb:
  docDb:
   resourceGroup: "azds-rg"
  graphDb:
   resourceGroup: "azds-rg"
  mongoDb:
   resourceGroup: "azds-rg"
dns:
  resourceGroup: "azds-rg"
  domain: "xiaodong.cloud"
  sslCert: "sslcert-dev-xiaodong-cloud"
trafficManager:
  resourceGroup: "azds-rg"
redis:
  resourceGroup: "azds-rg"