---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: example-com-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com-tls
  namespace: default
spec:
  commonName: example.com
  secretName: example-com-tls
  issuerRef:
    name: example-com-issuer