---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: "{{.Values.acr.name}}.azurecr.io/{{.Values.dns.image.name}}:{{.Values.dns.image.tag}}"
          resources:
            requests:
              cpu: "50m"
              memory: "25Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          args:
            - --source=service
            - --source=ingress
            - --domain-filter={{.Values.dns.domain}}
            - --provider=azure
            - --azure-resource-group={{.Values.dns.resourceGroup}}
            - --txt-owner-id={{.Values.aks.clusterName}}-{{.Values.aks.location}}
            - --log-level=debug
            - --policy=sync
          volumeMounts:
          - name: azure-config-file
            mountPath: /etc/kubernetes
            readOnly: true

      imagePullSecrets:
        - name: acr-auth

      volumes:
        - name: azure-config-file
          secret:
            secretName: external-dns-config-file
