apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: contributor-default
rules:
  - apiGroups: ["", "extensions"]
    resources: ["services","nodes","ingresses","pods","ingresses/status"]
    verbs: ["get","list","watch","create","update","delete","patch"]
  - apiGroups: [""]
    resources: ["configmaps","secrets","endpoints","events"]
    verbs: ["get","list","watch","create","update","delete","patch"]
