---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: "letsencrypt"
spec:
  commonName: "*.{{.Values.dns.domain}}"
  dnsNames:
    - "*.{{.Values.dns.domain}}"
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{.Values.dns.domainOwnerEmail}}"
    privateKeySecretRef:
      name: "letsencrypt"
    dns01:
      providers:
        - name: azure-dns
          domains:
            - "*.{{.Values.dns.domain}}"
          azuredns:
            email: {{.Values.dns.domainOwnerEmail}}
            clientID: {{.Values.aks.clusterServicePrincipalAppId}}
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            zoneName: {{.Values.dns.domain}}
            resourceGroupName: {{.Values.dns.resourceGroup}}
            subscriptionID: {{.Values.global.subscriptionId}}
            tenantID: {{.Values.global.tenantId}}

