---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: "cluster-issuer-{{.Values.global.envName}}-{{.Values.global.spaceName}}"
spec:
  acme:
    server: https://acme-staging-02.api.letsencrypt.org/directory
    email: "{{.Values.dns.domainOwnerEmail}}"
    privateKeySecretRef:
      name: "cluster-issuer-{{.Values.global.envName}}-{{.Values.global.spaceName}}"
      http01: {}
