---
kind: Certificate
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: "{{.Values.dns.sslCert}}"
spec:
  secretName: "{{.Values.dns.sslCert}}"
  issuerRef:
    name: "letsencrypt"
    kind: ClusterIssuer
  commonName: "*.{{.Values.dns.domain}}"
  dnsNames:
    - "*.{{.Values.dns.domain}}"
  acme:
    config:
      - dns01:
          provider: azure-dns
        domains:
          - "*.{{.Values.dns.domain}}"
