baseAppSettingsFile: "appsettings.Integration.json"
env:
  ASPNETCORE_ENVIRONMENT: Xiaodong
externalServices:
  - name: service-tree
    endpoint: "https://servicetreeppe.msftcloudes.com"
    resourceId: "294223da-1062-4786-b12c-157b25c248fc"

services:
  - name: product-catalog-api
    appId: "34118e01-f262-45e3-b4ee-12752716ae12"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: product-catalog-sync-job
    appId: "34118e01-f262-45e3-b4ee-12752716ae12"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: product-catalog-servicetreepush
    appId: "34118e01-f262-45e3-b4ee-12752716ae12"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: policy-catalog-api
    appId: "8e97a2d9-9aaa-461b-9130-269de2295b4d"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: policy-status
    appId: "8e97a2d9-9aaa-461b-9130-269de2295b4d"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: policy-impact
    appId: "8e97a2d9-9aaa-461b-9130-269de2295b4d"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: policy-impact-refresh-job
    appId: "8e97a2d9-9aaa-461b-9130-269de2295b4d"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: policy-engine
    appId: "8e97a2d9-9aaa-461b-9130-269de2295b4d"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: policy-service
    appId: "8e97a2d9-9aaa-461b-9130-269de2295b4d"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: extension-manager-job
    appId: "867a0305-60a6-40a3-ac8d-912c207ea9ae"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: ado-org-api
    appId: "66adda3e-dc2b-49ac-899a-fcde09b36eae"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}
  - name: product-catalog-web
    appId: "34118e01-f262-45e3-b4ee-12752716ae12"
    env:
      ASPNETCORE_ENVIRONMENT: {{.Values.global.spaceName}}